import combined,test

# USER INPUT

INPUT_CSV_FILENAME = "testCSVProcess.csv"

INTEREST_COLUMN_NAME = "Interested?"
LEADER_COLUMN_NAME = "Leader?"
NAME_COLUMN_NAME = "Name"

MIN_TEAM_SIZE = 2
MAX_TEAM_SIZE = 3
MAX_TEAMS_PER_PROJECT = 1
LEADERS_PER_TEAM = 1

OUTPUT_COLUMNS = ["Name","Random Question?"]
OUTPUT_FILENAME = "testCSVResult.csv"

RUN_USER_CODE = True
PRINT_RESULTS = True

RUN_TESTS = False


# DONT CHANGE FOLLOWING CODE

if RUN_USER_CODE:
    combined.run(
        INPUT_CSV_FILENAME,INTEREST_COLUMN_NAME,LEADER_COLUMN_NAME,NAME_COLUMN_NAME,MIN_TEAM_SIZE,
        MAX_TEAM_SIZE,MAX_TEAMS_PER_PROJECT,LEADERS_PER_TEAM,OUTPUT_FILENAME,OUTPUT_COLUMNS,PRINT_RESULTS
    )

if RUN_TESTS:
    test.runTests()

